docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - export FAIRWINDS_TOKEN=$FAIRWINDS_TOKEN_VALUE
    - apk update
    - apk add bash
  script:
    - |
      wget https://insights.fairwinds.com/v0/insights-ci-2.1.0.sh
      echo "c7f9e6d6120998ea517419ce4e3de7039af3991ccb3392271dd91754b300d5e2 insights-ci-2.1.0.sh" > insights-ci-2.1.0.sh.sha256
      sha256sum -c insights-ci-2.1.0.sh.sha256
      chmod +x insights-ci-2.1.0.sh
      bash
      image_version=2.1.3 ./insights-ci-2.1.0.sh