# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -L https://staging.insights.fairwinds.com/v0/insights-ci-2.1.0.sh > insights-ci.sh
      echo "c7f9e6d6120998ea517419ce4e3de7039af3991ccb3392271dd91754b300d5e2 *insights-ci.sh" | shasum -a 256 --check
      chmod +x insights-ci.sh
      ./insights-ci.sh
  env:
    FAIRWINDS_TOKEN: $(FAIRWINDS_TOKEN)
