### 
PUT https://staging.insights.fairwinds.com/v0/organizations/vvezani/github/config
Content-Type: application/json
Accept: application/json
Authorization: Bearer NHYNSWyYzQChQFtbFmFfz0Cuh0ydKenqMe_xlsWlSBe2SDtAB88ZC527wqK2n3ax

{
    "hooksEnabled": true
}

### 
PUT https://be-vv-fwi-1430-pu.k8s.insights.fairwinds.com/v0/organizations/acme-co/github/config
Content-Type: application/json
Accept: application/json
Authorization: Bearer thisisanadmintoken

{
    "hooksEnabled": true
}
