apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-3
  labels:
    app: nginx-deployment-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment-3
  template:
    metadata:
      labels:
        app: nginx-deployment-3
    spec:
      containers:
        - name: nginx-deployment-3
          image: alpine:3.13.0
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            capabilities: {}
