apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-2
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: alpine:3.13.0
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: true
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            capabilities: {}
          resources:
            limits:
              cpu: 100m # TODO: Set this to the maximum amount of CPU you want your workload to use
              memory: 256Mi # TODO: Set this to the maximum amount of memory you want your workload to use
            requests:
              cpu: 100m # TODO: Set this to the amount of CPU you want to reserve for your workload
              memory: 256Mi # TODO: Set this to the maximum amount of memory you want your workload to use

