apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-0
  labels:
    app: nginx-deployment-0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment-0
  template:
    metadata:
      labels:
        app: nginx-deployment-0
    spec:
      containers:
        - name: nginx-deployment-0
          image: nginx:1.27.0
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            capabilities: {}
          resources:
            limits:
              cpu: 100m # TODO: Set this to the maximum amount of CPU you want your workload to use
            requests:
              cpu: 100m # TODO: Set this to the amount of CPU you want to reserve for your workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
  labels:
    app: nginx-deployment-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment-1
  template:
    metadata:
      labels:
        app: nginx-deployment-1
    spec:
      containers:
        - name: nginx-deployment-1
          image: nginx:1.27.0
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            capabilities: {}
          resources:
            limits:
              cpu: 100m # TODO: Set this to the maximum amount of CPU you want your workload to use
            requests:
              cpu: 100m # TODO: Set this to the amount of CPU you want to reserve for your workload
