apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-req-limits
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx@sha256:295c7be079025306c4f1d65997fcf7adb411c88f139ad1d34b537164aa060369
        ports:
        - containerPort: 80