apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
automountServiceAccountToken: true

---
# This fails because automounting is true for both the pod and ServiceAccount.
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  automountServiceAccountToken: true
  serviceAccountName: test
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: 100m # TODO: Set this to the maximum amount of CPU you want your workload to use
