name: Fairwinds Insights
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FAIRWINDS_TOKEN: ${{ secrets.FAIRWINDS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fairwinds Insights
        run: |
          curl -L https://be-vv-automa.k8s.insights.fairwinds.com/v0/insights-ci-4.2.0.sh > insights-ci.sh
          echo "99662f37b973016854cb125f0b8733defd00288fe7f1a6a6477fa3875aec512a *insights-ci.sh" | shasum -a 256 --check
          chmod +x insights-ci.sh
          ./insights-ci.sh
