name: Fairwinds Insights
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FAIRWINDS_TOKEN: ${{ secrets.FAIRWINDS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fairwinds Insights
        run: |
          curl -L https://staging.insights.fairwinds.com/v0/insights-ci-2.2.0.sh > insights-ci.sh
          echo "1632dca8b4dc043d2a62b1c37fd7a8ac034cb22b359c7119e5c11db9515180b2 *insights-ci.sh" | shasum -a 256 --check
          chmod +x insights-ci.sh
          ./insights-ci.sh